from rest_framework import viewsets, serializers

from flix_tube_backend.settings import MEDIA_ROOT
# from likeapp.models import Like
from .models import VideoContent
import os
from moviepy.editor import VideoFileClip
import tempfile
import shutil
from PIL import Image
import subprocess
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
import datetime
from likes.models import Like
# from video_chat import VideoChat

class Video_contentSerializer(serializers.ModelSerializer):
    up_likes_count = serializers.SerializerMethodField()
    down_likes_count = serializers.SerializerMethodField()
    liked_up = serializers.SerializerMethodField()   # Berechnet, ob der Benutzer ein 'up' Like gesetzt hat
    liked_down = serializers.SerializerMethodField()
    
    
    class Meta:
        model = VideoContent
        fields = ('id', 'title', 'description', 'video', 'video_imgs', 'preview_gif', 'view_count','down_likes_count','up_likes_count','liked_up','liked_down')
        read_only_fields = ['created_at'] 
    
    
    """
    Checks if the authenticated user has liked (up vote) the given video.

    :param obj: The video object for which the 'up like' status is being checked.
    :return: True if the user has liked (up voted) the video, False otherwise.
    """
    def get_liked_up(self, obj):
        user = self.context['request'].user
        return Like.objects.filter(video=obj, user=user, up_like=True).exists()


    """
    Checks if the authenticated user has disliked (down vote) the given video.
    :param obj: The video object for which the 'down like' status is being checked.
    :return: True if the user has disliked (down voted) the video, False otherwise.
    """
    def get_liked_down(self, obj):
        user = self.context['request'].user
        return Like.objects.filter(video=obj, user=user, down_like=True).exists()


    """
    Returns the count of up likes (up votes) for the given video.
    :param obj: The video object for which the up like count is being retrieved.
    :return: The number of up likes for the specified video.
    """
    def get_up_likes_count(self, obj):    
        count = Like.objects.filter(video=obj, up_like=True).count()
        print("Logging up likes count: ", count)  # Zum Debuggen
        return count


    """
    Returns the count of down likes (dislikes) for the given video.
    :param obj: The video object for which the down like count is being retrieved.
    :return: The number of down likes for the specified video.
    """
    def get_down_likes_count(self, obj):
        count = Like.objects.filter(video=obj, down_like=True).count()
        print("Logging down likes count: ", count)  # Zum Debuggen
        return count
    
    
    """
    Creates a thumbnail image from the middle frame of the given video file.
    - Saves the video temporarily, extracts a frame at the midpoint, 
    and saves it as a thumbnail image in the 'video_imgs' directory.
    :param video_file: The uploaded video file from which the thumbnail will be created.
    :return: The absolute file path of the saved thumbnail image.
    """
    def create_thumbnail(self, video_file):
        with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as temp_video:
            for chunk in video_file.chunks():
                temp_video.write(chunk)
        temp_video_path = temp_video.name
        try:
            clip = VideoFileClip(temp_video_path)
            frame = clip.get_frame(clip.duration / 2)
            clip.close()
            thumb_dir = os.path.join(MEDIA_ROOT, 'video_imgs')  
            if not os.path.exists(thumb_dir):
                os.makedirs(thumb_dir) 
            thumb_path = os.path.join(thumb_dir, os.path.basename(temp_video_path) + '_thumbnail.jpg')
            image = Image.fromarray(frame)
            image.save(thumb_path)
            
            return thumb_path
        finally:
            os.unlink(temp_video_path) 


    """
    Creates a GIF from a segment of the provided video file using FFmpeg.
    - The GIF is generated by extracting a 4-second segment starting at 1 second into the video.
    - The command uses FFmpeg to scale the GIF and apply a palette for optimized color usage.
    :param video_path: The file path of the video from which the GIF will be created.
    :param output_gif_path: The file path where the generated GIF will be saved.
    """
    def create_gif(self, video_path, output_gif_path):
        cmd = [
            'ffmpeg',
            '-ss', '1', 
            '-t', '4',    
            '-i', video_path,
            '-vf', 'fps=1,scale=320:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse',
            '-loop', '0',
        output_gif_path
        ]
        subprocess.run(cmd, text=True)


    """
    Creates a new VideoContent instance by processing the uploaded video file.
    - If no video image is provided, a thumbnail is generated from the video.
    - The video is temporarily saved, and a GIF preview is created from the video.
    - After processing, the temporary video file is deleted. 
    :param validated_data: The validated data containing the video and associated fields.
    :return: The created VideoContent instance.
    """
    def create(self, validated_data):
        video_file = validated_data.get('video')
        video_img = validated_data.get('video_imgs')
        print('img',video_img)
        print('imgs',validated_data.get('video_imgs')) 
        if not validated_data.get('video_imgs'):
                print("zweite 2 if abfrage")
                thumbnail_path = self.create_thumbnail(video_file)
                print("zweite 2 if abfrage",thumbnail_path)
                validated_data['video_imgs'] = thumbnail_path
        temp_path = default_storage.save('tmp/some_prefix_' + video_file.name, ContentFile(video_file.read()))
        full_temp_path = os.path.join(default_storage.location, temp_path)
        print('full_temp_path',full_temp_path)
        base_name = os.path.splitext(video_file.name)[0] 
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")  
        output_gif_path = os.path.join('media/video_gifs', f'{timestamp}_{base_name}.gif')

        self.create_gif(full_temp_path, output_gif_path)
        video_content = VideoContent.objects.create(
            title=validated_data['title'],
            description=validated_data.get('description', ''),
            video = validated_data.get('video', None),
            video_imgs = validated_data.get('video_imgs', None),
            preview_gif = validated_data.get('video_gifs', None),
        )
        os.remove(full_temp_path)
        default_storage.delete(temp_path)
        video_content.save()
        return video_content